### ISSUE TITLE
Extent methods for na.action

### ISSUE THREAD

**Issue by andybega** [andybega/spduration#10]
Extent the spdur methods and spdur to accomodate various na.action options.

See napredict.

**Comment by ulfelder** [comment]
After tinkering with the package this morning, I was going to open an issue on this topic, but I see you've already got one, so I'll just hang a comment here to say: yes, please!

**Comment by andybega** [comment]
Thanks Jay, I'll try to put some time into this in the next few days. With your use case, does what you need essentially correspond to the behavior of `na.exclude`, i.e. estimation is like `na.omit`, but for `predict` and `resid` methods, the output would be padded for any NA's in the input, thus returning a output vector of same length as in the input data rows?

**Comment by ulfelder** [comment]
Yes, `na.exclude` is the behavior I'm after.

**Comment by andybega** [comment]
This should work as a workaround until the package is updated:

```r
data(coups)
dur.coups <- add_duration(coups, "succ.coup", unitID="gwcode", tID="year",
                                              freq="year")
mdl <- spdur(duration ~ polity2, atrisk ~ polity2, data=dur.coups, silent = TRUE,
                        na.action = na.exclude)
length(predict(mdl))
length(napredict(mdl$na.action, predict(mdl)))
```

The second set of predictions should be 5828 long, padded with NA's.

**Comment by andybega** [comment]
`predict` will work with `na.action = na.exclude` now. It's not on CRAN yet, but if you install from GitHub it should work.
